#!/usr/bin/env bash

STATE="$XDG_RUNTIME_DIR/i3-workspace-outputs.json"

[ -f "$STATE" ] || exit 0

active_outputs=$(
    xrandr --query |
    awk '/ connected/ && $0 ~ /[0-9]+x[0-9]+\+/ {print $1}'
)

jq -r '.[] | [.name, .output] | @tsv' "$STATE" |
while IFS=$'\t' read -r workspace output; do
    if grep -qxF "$output" <<< "$active_outputs"; then
        i3-msg "[workspace=\"$workspace\"] move workspace to output \"$output\"" > /dev/null 2>&1
    fi
done
