# make sure the color is the same in tmux sessions
# set-option -g default-terminal "term-256color"
# set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"

set-environment -g GPG_TTY $TTY

# prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# mouse
set -g mouse on

set-option -g history-limit 5000

set -g renumber-windows on

# split window
bind-key "\\" split-window -hc "#{pane_current_path}"
bind-key "-" split-window -vc "#{pane_current_path}"

bind Space last-window

# Vim-style pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key > swap-window -d -t +1
bind-key < swap-window -d -t -1

unbind-key r
bind-key r command-prompt -I "#W" "rename-window '%%'"

unbind-key ,
bind-key , choose-tree

# copy mode
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '60' # unit: second
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'

run '~/.config/tmux/plugins/tpm/tpm'
